# Generated by Django 4.0.5 on 2022-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='books.author', verbose_name='Авторы'),
        ),
    ]
