# Generated by Django 4.0.5 on 2022-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, height_field=350, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображения', width_field=150),
        ),
    ]
